### ISSUE TITLE
Load new javascript

### ISSUE THREAD

**Issue by hjJunior** [sudojesse/dynamic-page#1]
How can and where can I put javascript to load
I have custom javascript for each page, how can I load them different for each page?
Please help me

I tried to put inside of `<div id="guts">` but not loaded after ajax change page

**Comment by hjJunior** [comment]
Example
When changed page to about page do this:

`<script type="text/javascript">
	alert("loaded about!");
</script>`

**Comment by moeenio** [comment]
@hjJunior Inside your loadContent function, get the scripts with a class added to them, then replace them with the new page scripts.

**Comment by moeenio** [comment]
Did I help @hjJunior ?
